aws:
    region: eu-central-1
    role_arn: arn:aws:iam::785668202743:role/TrafficGuardStreamConsumer
kinesis:
    video:
        stream:
            content_type: video/h264
            name: traffic-guard
film:
    watcher:
        save_nth_frame: 5
        bucket_name: traffic-guard-frames
        folder: source_images
        monitor:
            render: false #-Djava.awt.headless=false - add this parameter if renderer = true
            width:  1280
            height: 720
        wait:
            retry:
                read: 30 #seconds